// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MouseMovementContext.Models;

public partial class mousemovementContext : DbContext
{
    public mousemovementContext(DbContextOptions<mousemovementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Coordinate> Coordinates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Coordinate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("coordinates_pkey");

            entity.ToTable("coordinates");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Data)
                .HasColumnType("json")
                .HasColumnName("data");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}